### ISSUE TITLE
Possible UMD bug

### ISSUE THREAD

**Issue by msssk** [dojo/loader#24]
I tried to load [cldrjs](https://github.com/rxaviers/cldrjs) and the module resolved to a new, empty object.

Using Dojo 1's loader it works fine.

Install 'cldrjs' with bower or npm, then `require(['cldrjs/dist/cldr'], ...)`

**Comment by edhager** [comment]
@msssk, can you provide a test file?

**Comment by msssk** [comment]
Adjust paths as necessary:
https://gist.github.com/msssk/25bcdb174158e9b379d2

**Comment by jdonaghue** [comment]
It turns out that this was not an issue with loading UMD modules specifically. The issue was more isolated to loading modules in an AMD environment where only a factory is defined with no dependencies. Essentially, the loader was not capturing the result of the factory's execution under that specific scenario leaving the default empty object as the modules resolution.

Loading this module would result in the same error:
```js
define(function () {
    //...
});
```

The solution (along with tests) can be found in this commit https://github.com/jdonaghue/loader/commit/6b4d6a7b7d89b696cd6ea83e2cc3578e9816e3a1
