### ISSUE TITLE
Can the differentiation commonjs / amd go to the loader ?

### ISSUE THREAD

**Issue by sebilasse** [dojo/loader#29]
I am a bit confused how to use the loader the right way (just some words in the readme would be nice) – especially I wondered why I had to write the same code used in different submodules as well in my own submodule and if it couldn't go to the loader.
The snippet I am talking about is for example in i18n

```typescript
const getJson: (...paths: string[]) => Promise<{}[]> = (function () {
	if (has('host-node')) {
		return function (...paths: string[]): Promise<{}[]> {
			return load(require, ...paths);
		};
	}
	else if (typeof define === 'function' && define.amd) {
		return function (...paths: string[]): Promise<{}[]> {
			return load(require, 'dojo-core/request').then(function ([ request ]: [ typeof coreRequest ]): Promise<{}> {
				return Promise.all(paths.map(function (path: string): Promise<{}> {
					return request.get(path + '.json', { responseType: 'json' }).then(function (response) {
						return response.data;
					});
				}));
			});
		};
	}
	else {
		throw new Error('Unknown loader');
	}
})();
```

If I use the loader in TS projects which can build both commonjs and amd 
do I have to write the same ?
Couldn't the loader do this ?
I don't know if my use case is to specific - I want to load "multilanguage data modules" at runtime depending on a recognized language (for https://github.com/redaktor/nlp) ...

**Comment by edhager** [comment]
Hi @sebilasse,

A [ticket](22) has been written to update the readme.  It definitely needs some work.

The primary goal of the Dojo 2 loader project is to produce an AMD loader that is as small as possible with zero runtime dependencies.  Take a look at the [Loader Proposal](https://docs.google.com/document/d/1-gbawq5nhi1GuYuVMoTJBFAzESaqgYKlS_aLzHzaAXs/edit#heading=h.cdfu7lqomlpn) for some background on the loader's design.  In order to keep the loader small with no dependencies, the `require()` function takes a callback function as the last parameter rather than return a promise.    

The other Dojo 2 components use promises as much as possible and dojo-core provides a promise implementation for all to use.  The `dojo-core/load` module is an adapter that uses the loader's require function to dynamically load modules but returns a promise rather than requiring a callback to be passed in.  The `dojo-core/load` module is also written to support more than the Dojo 2 loader; it works with other AMD loaders and the Node.js loader.

Ok, that explains why `dojo-core/load` is a thing but the code you referenced is doing even more than just using `load` as a promise-based `require` function.  The code you are referencing has two additional requirements:  (1) load a json file and (2) support both an AMD loader and the Node.js loader.

The Node.js loader's `require` function will load a JSON file just fine but is synchronous so the first bit of code is using `dojo-core/load` to adapt the Node.js loader.  An AMD loader expects all files that it loads to be AMD modules so `dojo-core/request` is needed to load a JSON file. `dojo-core/load` is being used to dynamically load the `request` only when it is needed.

At this point we can't move the code you provided into the loader because it would add runtime dependencies and/or increase the size of the loader code.

Do you have all of the same requirements that the i18n module has:
* Support any AMD loader.
* Support the Node.js loader.
* Must use promises.

If you have all of those requirements then you probably need to do something similar in your code.  Otherwise, you may be able to use something more simple.  For example, the Dojo loader works fine in Node.js so you could write your code to only support the Dojo loader and if you don't mind using callbacks, you could use `require` directly rather than using `dojo-core/load`.

Let me know if any of this is confusing.

**Comment by sebilasse** [comment]
@edhager : :+1:  ok, thank you. Not confused at all.
Let's forget the promises then.
What I meant is something like

```typescript
declare var require/*: Require*/;
declare var define: any;
import has = require('../../dojo/has');
import m = require('./en/index');

// see also https://github.com/dojo/loader/issues/29 :
// TODO - might change to dojo loader plugin ...
function loadData(lang:string, keys:string[], callback?:(data:any) => any) {

if (has('host-node')) {
    const modules:any[] = [];
    keys.forEach(function(key) {
      var data: typeof m = require(key);
      modules.push(data);
    });
    if (modules.length === keys.length && callback) {
      callback.apply(this, modules);
    } else if (!callback) {
      return modules;
    } else {
      throw new Error('Could not load module: '+keys.join(', '));
    }
  } else if (typeof define === 'function' && define.amd) {
    require(keys,
      (modules: typeof m) => {
        if (callback) { callback.apply(this, modules); }
      },
      (err: Error) => {
        throw err;
      }
    );
  } else {
    throw new Error('Unknown loader');
  }
```

**Comment by dylans** [comment]
In this case though, we really want to run different code paths based on whether we have Node available or not. It's not just detecting the module loading system, but assuming that if we have node, then we want to use node-specific modules, otherwise we want to use something else.

I mean, we could add a feature test for amd, so it would become else if (has('amd')) { ...
in order to reduce some of the boilerplate.

That said, I'm probably missing what you're going for...

**Comment by kitsonk** [comment]
@dylans why wouldn't we want to use [jrburke/amdefine](https://github.com/jrburke/amdefine).  I recently ran into issues where I wanted to ensure that my modules were fully loadable under CommonJS without requiring an AMD loader.  While UMD module packaging sort of works, the problem that arises is that if you still want to utilise AMD plugin features but still want your code to be isomorphic.

As mentioned in the `README` for `amdefine`, `r.js` can build out the minimal boilerplate, I am sure we could leverage something similar for Dojo 2.

**Comment by dylans** [comment]
@kitsonk I know we considered it when working on the proposal ( https://docs.google.com/document/d/1-gbawq5nhi1GuYuVMoTJBFAzESaqgYKlS_aLzHzaAXs/edit#heading=h.mknz10lo6jxp ), but I don't see a decision noted. Perhaps @bryanforbes or @edhager remember why we didn't use amdefine.

**Comment by sebilasse** [comment]
:flashlight: like the idea of amdefine. Could be a solution.
Let me describe what I am doing - maybe this is outside the scope of dojo.
There are a few modules for @redaktor which will be standalone in the sense that TypeScript will compile them to both AMD and commonjs modules. 
So I could publish the commonjs to npm for quick node only use (for dummies) and use the AMD myself ;) or let people use it in the browser.

As said if I could compile AMD only and it would work 
> under CommonJS without requiring an AMD loader

this could be the solution.

**Comment by kitsonk** [comment]
We are structuring our packages to make it easy to consume them being fairly loader agnostic.  There maybe more work we need to do, but we would target specific issues and address those, so this specific issue we will consider closed.
